# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import auth_pb2 as auth__pb2


class TokenValidationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.validate = channel.unary_unary(
                '/TokenValidation/validate',
                request_serializer=auth__pb2.tokeninput.SerializeToString,
                response_deserializer=auth__pb2.result.FromString,
                )


class TokenValidationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def validate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TokenValidationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'validate': grpc.unary_unary_rpc_method_handler(
                    servicer.validate,
                    request_deserializer=auth__pb2.tokeninput.FromString,
                    response_serializer=auth__pb2.result.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TokenValidation', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TokenValidation(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def validate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TokenValidation/validate',
            auth__pb2.tokeninput.SerializeToString,
            auth__pb2.result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
